project_id = "aufycarwflhsdgszbnop"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.vision-scanner]
verify_jwt = false